name: 🔁 Auto Deploy Static Site

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to NGINX folder using rsync
        run: |
          rsync -av --delete ./ /home/azureuser/flamesgame/